/*
opioid_names.do
===============
Identify opioid drug records in the merged DIP/HC drug file and attach
the appropriate MME conversion factor to each.

The script proceeds in five phases:

  Phase 1  Search for opioid names in the ingredient field (HC records)
           and in drug_brand_nm (DIP-only records).

  Phase 2  For DIP-only records whose ingredient is "Unknown Generic Drug",
           apply the manually parsed brand-name lookup (parse_brand_name.csv)
           to supply ingredient, strength, strength_unit, and dosage_value.

  Phase 3  For records still missing a numeric strength after Phase 2,
           apply the manually parsed strength lookup (parse_strength.csv)
           to supply strength, strength_unit, and where available, form and
           route information.

  Phase 4  Determine the route of administration for each record (1=oral/
           rectal, 2=patch, 3=injectable, 4=nasal/spray, 5=buccal/sublingual).
           Route is needed both to select the correct MME conversion factor
           and to interpret DSPD_QTY correctly.

  Phase 5  Compute a per-unit strength factor, reduce to one row per
           DIN/PIN, and merge with the MME conversion factor table (mme.csv).

Background on the manual parsing files
---------------------------------------
parse_brand_name.csv
    Generated by exporting DIP-only records whose ingredient was
    "Unknown Generic Drug" to Excel and manually looking up each drug.
    Contains: din_pin, ingredient, strength, strength_unit, dosage_value.
    Note: "hydromorphine" in some source records is a typo for hydromorphone;
    this is corrected in the CSV.

parse_strength.csv
    Generated by exporting records still missing numeric strength after
    Phase 2 to Excel.  About one-third required online lookup.  Some records
    have ambiguous quantity interpretation (see README for details on
    injectable vials/powders).
    Contains: din_pin, gen_drug_strgth, gen_dsg_form, gen_entry_route_dscr.

Route codes in route2 (encoded from Health Canada route field)
---------------------------------------------------------------
The numeric values below refer to the Stata encoded levels of the route
variable from the HC route segment.  The mapping was established by
inspecting -codebook route2- after encoding.  Key values used here:
  4  = ORAL          14 = INTRAMUSCULAR   45 = INTRAVENOUS
  59 = INTRATHECAL   68 = NASAL           73 = RECTAL
  79 = SUBLINGUAL    84 = SUBCUTANEOUS    86 = BUCCAL   98 = TRANSDERMAL

Outputs
-------
  $dir\dip_hc_opioids.dta  – one row per din_pin × route combination,
                              with factor (per-unit MME before cf) and
                              cf (conversion factor from mme.csv).
                              MME per prescription = factor × cf × quantity.

Copyright 2024 Province of British Columbia
Licensed under the Apache License, Version 2.0
http://www.apache.org/licenses/LICENSE-2.0
*/

/* -----------------------------------------------------------------------
   Phase 1: Flag opioid records
   ----------------------------------------------------------------------- */

/* Load the opioid name list, sorting by length so that longer names
   overwrite shorter ones when both match (avoids "COD" matching "CODEINE"
   records and then being overwritten only if we process longest first)   */
clear
import delimited using "$dir\list_of_opioids.txt", varnames(nonames) clear
gen _len = length(v1)
sort _len
local druglist ""
forval i = 1/`=_N' {
    local druglist "`druglist' `=v1[`i']'"
}
drop _len

/* Drugs that look like opioids but are not (contain opioid-adjacent names
   as substrings of a non-opioid active ingredient)                        */
local not_opioid "APOMORPHINE IPRATROPIUM TIOTROPIUM HELIOTROPIUM"

use "$dir\dip_hc.dta", clear

gen yikes      = 0          // opioid name found in drug_brand_nm only
gen opioid     = 0          // opioid name found in ingredient
gen opioid_name = ""

foreach d of local druglist {
    di "Checking: `d' — $(c(current_time))"

    /* Match in the HC ingredient field */
    replace opioid      = 1    if strpos(ingredient,    "`d'") > 0
    replace opioid_name = "`d'" if strpos(ingredient,   "`d'") > 0 ///
        & (strlen("`d'") > strlen(opioid_name) | missing(opioid_name))

    /* Match in the DIP brand name field */
    replace yikes = 1 if strpos(drug_brand_nm, "`d'") > 0
}

/* Remove false positives */
foreach d of local not_opioid {
    replace opioid      = 0  if strpos(ingredient,    "`d'") > 0
    replace yikes       = 0  if strpos(drug_brand_nm, "`d'") > 0
    replace opioid_name = "" if strpos(ingredient,    "`d'") > 0
}

/* Keep confirmed opioids + DIP-only brand-name matches for further review */
keep if opioid | (yikes & ingredient == "Unknown Generic Drug")

save temp, replace

/* -----------------------------------------------------------------------
   Phase 2: Apply manual brand-name parsing
   For DIP-only records whose ingredient is "Unknown Generic Drug", the
   manually parsed file supplies ingredient, strength, strength_unit, and
   dosage_value.  joinby with update fills missing values in temp from the
   parse file without overwriting populated fields.
   ----------------------------------------------------------------------- */

import delimited "$dir\parse_brand_name.csv", clear
gen opioid_name  = ingredient
gen opioid       = 1
gen dosage_value = 0

/* joinby update: for records in both files, update missing values in temp
   (the "using" dataset here) from parse_brand_name (the master)           */
joinby din_pin using temp, unmatched(using) update
drop _merge

save temp, replace

/* -----------------------------------------------------------------------
   Phase 3: Apply manual strength parsing
   For records still missing numeric strength, the parse_strength file
   provides gen_drug_strgth, gen_dsg_form, and gen_entry_route_dscr.
   ----------------------------------------------------------------------- */

import delimited "$dir\parse_strength.csv", clear

joinby din_pin using temp, unmatched(using) update

replace strength = gen_drug_strgth ///
    if missing(strength) | strength == 0

/* Diagnostic: list drugs still missing strength (informational only) */
di "Drugs still missing strength after Phase 3:"
tab drug_brand_nm if strength == 0 | missing(strength)

/* -----------------------------------------------------------------------
   Phase 4: Determine route of administration
   route codes: 1=oral/rectal  2=patch  3=injectable  4=nasal/spray
                5=buccal/sublingual  0=undetermined

   Priority: explicit route2 codes from HC take precedence; then drug
   name strings; then form strings; fallback for methadone and remaining
   unknowns at the end.
   ----------------------------------------------------------------------- */

replace route2 = 0 if missing(route2)
gen route = 0

/* --- Oral / Rectal (route=1) --- */
replace route = 1 if                                      ///
    inlist(route2, 4, 73, 79, 86)                       | ///
    strpos(gen_entry_route_dscr, "ORAL")    > 0         | ///
    strpos(gen_entry_route_dscr, "RECTAL")  > 0         | ///
    strpos(gen_dsg_form,         "TAB")     > 0         | ///
    strpos(drug_brand_nm,        "TAB")     > 0         | ///
    strpos(drug_brand_nm,        "SUPPOSITORY") > 0     | ///
    strpos(drug_brand_nm,        "ORAL")    > 0         | ///
    strpos(drug_brand_nm,        "COUGH")   > 0

/* --- Transdermal patch (route=2) --- */
replace route = 2 if                                      ///
    inlist(route2, 98)                                  | ///
    strpos(drug_brand_nm, "PATCH") > 0

/* --- Injectable (route=3) --- */
/* Note: some tablet formulations are recorded under injectable route codes
   in the HC data; these are caught by the TAB override for route=1 above.  */
replace route = 3 if                                      ///
    inlist(route2, 14, 45, 59, 84)                      | ///
    strpos(drug_brand_nm,        "INJ")   > 0           | ///
    strpos(drug_brand_nm,        "INTRA") > 0           | ///
    strpos(gen_entry_route_dscr, "INJ")   > 0

/* --- Nasal / Spray (route=4) --- */
replace route = 4 if                                      ///
    inlist(route2, 68)                                  | ///
    strpos(gen_entry_route_dscr, "NASAL") > 0          | ///
    strpos(drug_brand_nm,        "SPRAY") > 0

/* --- Buccal / Sublingual (route=5) --- */
replace route = 5 if                                      ///
    inlist(route2, 4, 86)                               | ///
    strpos(drug_brand_nm, "BUCCAL")     > 0            | ///
    strpos(drug_brand_nm, "SUBLINGUAL") > 0

/* --- Combination injectables (opioid + local anaesthetic) --- */
/* Online search confirmed these four DINs are all injectable products   */
replace route = 3 if route == 0                           ///
    & (strpos(drug_brand_nm, "HYDROMORPHONE") > 0       | ///
       strpos(drug_brand_nm, "MORPHINE")      > 0       | ///
       strpos(drug_brand_nm, "FENTANYL")      > 0)      ///
    & (strpos(drug_brand_nm, "BACLOFEN")      > 0       | ///
       strpos(drug_brand_nm, "CLONIDINE")     > 0       | ///
       strpos(drug_brand_nm, "BUPIVICAINE")   > 0       | ///
       strpos(drug_brand_nm, "BUPIVACAINE")   > 0)

/* --- Methadone fallback (oral maintenance — always route=1) --- */
replace route = 1 if strpos(drug_brand_nm, "METHADONE") > 0 & route == 0

/* --- Capsule and suppository fallbacks --- */
replace route = 1 if strpos(drug_brand_nm, "CAP") > 0 & route == 0
replace route = 1 if strpos(drug_brand_nm, "SUP") > 0 & route == 0

/* --- Remaining unknowns: by inspection, all are injectable --- */
replace route = 3 if route == 0

/* Flag vial-dispensed injectables (quantity interpretation differs) */
gen vial = (strpos(drug_brand_nm, "VIAL") > 0) | (dosage_unit == "VIAL")

/* -----------------------------------------------------------------------
   Merge with MoH file to pick up any additional drug_strength_unit info.
   The MoH file adds no extra route or form information not already captured
   above, but does supply strength units for a small number of DIP drugs.
   ----------------------------------------------------------------------- */

drop _merge
merge m:1 din_pin using "$dir\moh_opioid_list.dta"
drop if _merge == 2   // drop MoH-only records (not in our opioid set)
drop _merge

/* Apply MoH strength unit where HC value is missing */
replace strength_unit = drug_strength_unit if !missing(drug_strength_unit)

/* -----------------------------------------------------------------------
   Manual corrections for specific DINs with anomalous strength/unit data
   (identified by inspecting implausible per-prescription MME values)
   ----------------------------------------------------------------------- */

replace strength = strength/1000 if dosage_unit   == "L" & strength_unit == "MG"
replace dosage_unit = "ML"  if dosage_unit   == "L" & strength_unit == "MG"

gen temp_code  = dosage_unit   == "L" & strength_unit == "G"
replace dosage_unit = "ML"  if temp_code
replace strength_unit = "ML"  if temp_code
drop temp_code

replace dosage_unit   = "ML" if strength_unit == "%"
replace strength_unit = "MG" if strength_unit == "%"


/* DIN 95680 — opium tincture: strength unit missing */
replace strength_unit = "MG" if din_pin == 95680

/* DINs 2249391/2249413/2249421/2249448 — RAN Fentanyl patches:
   strength listed in HC as total mcg per patch but PharmaNet records
   the release rate; correct to release rate (mcg/hr)                     */
replace strength      = 25   if din_pin == 2249391
replace strength      = 50   if din_pin == 2249413
replace strength      = 75   if din_pin == 2249421
replace strength      = 100  if din_pin == 2249448
replace strength_unit = "MCG" if inlist(din_pin, 2249391, 2249413, 2249421, 2249448)

/* -----------------------------------------------------------------------
   Phase 5: Compute per-unit strength factor

   For most forms, dspd_qty is the number of units dispensed (tablets,
   patches, mL for liquids).  The factor converts one dispensed unit into mg
   of the active opioid:

     tablets, oral liquids:  factor = strength / dosage_value
                             (e.g. 5 mg per 5 mL → factor = 1 mg/mL)
     patches:                factor = strength  (mcg/hr per patch)
     injectables (vial):     factor = strength  (mg per vial)
     injectables (volume):   factor = strength / dosage_value  (mg per mL)

   Special cases are handled below.
   ----------------------------------------------------------------------- */

gen factor = strength

/* Oral and volume-based injectable: divide by dosage volume */
replace factor = strength / dosage_value ///
    if inlist(route, 1, 3) & dosage_value != 0 & !missing(dosage_value)

/* Vial-based injectables: use full vial strength */
replace factor = strength if route == 3 & vial

/* DINs for pre-filled syringes where quantity = number of syringes */
replace factor = strength if inlist(din_pin, 2483084, 2483092, 9858127, 9858128)

/* DIN 2113031 — butorphanol nasal spray: policy manual says "number of doses";
   per product monograph, 1 dose = 1.7 mg                                 */
replace factor = 1.7 if din_pin == 2113031

/* -----------------------------------------------------------------------
   Prepare the MME conversion factor table
   mme.csv has columns: med_name, units, mme_route, cf
   Standardise to upper case to allow string matching with opioid_name.
   ----------------------------------------------------------------------- */

save temp, replace

import delimited "$dir\mme.csv", clear
keep med_name units mme_route cf
rename med_name opioid_name
replace opioid_name  = upper(opioid_name)
rename units strength_unit
replace strength_unit = upper(strength_unit)
duplicates drop
export delimited "$dir\mme", replace
save "$dir\mme", replace

use temp, clear

/* -----------------------------------------------------------------------
   Reduce to one row per din_pin, then determine mme_route for the merge.

   Most opioids use a single conversion factor regardless of route.
   Exceptions that have route-specific factors in mme.csv:
     BUPRENORPHINE, FENTANYL, BUTORPHANOL
   For all others, mme_route is set to 1 (oral equivalent) so the merge
   finds the single entry in mme.csv.
   ----------------------------------------------------------------------- */

keep din_pin opioid_name factor route strength_unit strength hc_or_dip
duplicates drop

gen mme_route = route
replace mme_route = 1 if !inlist(opioid_name, "BUPRENORPHINE", "FENTANYL", "BUTORPHANOL")

/* -----------------------------------------------------------------------
   Merge with the MME conversion factor table
   ----------------------------------------------------------------------- */

save temp, replace

clear
import delimited "$dir\mme.csv"
save "$dir\mme", replace

use temp, clear

merge m:1 opioid_name mme_route strength_unit using "$dir\mme"
drop _merge

/* Records with missing factor (strength not resolved) are dropped here.
   Investigate any unexpected drops via the diagnostic tab above.          */
drop if missing(factor)

save "$dir\dip_hc_opioids", replace
di "opioid_names complete — $(c(current_time))"
di "  ${c(N)} din_pin × route records saved to dip_hc_opioids.dta"
